### PR TITLE
Update qiskit-addon-projectq to qiskit-addon-sympy status

### PR DESCRIPTION
**Pull request by yaelbh**
A single commit with a bunch of improvements, equivalent to work recently done in the sympy addon. This includes open and closed pull requests in qiskit-addon-sympy, and an open qiskit-addon-projectq pull request (#8) about providers.

### CODE REVIEW

**Comment by yaelbh** [comment]
I see that Travis failed for Python 3.5 because it cannot find the cpp simulator. It's strange because I thought that the cpp simulator was automatically compiled upon qiskit installation. It's even stranger because the checks pass for Python 3.6. @diego could you please advise?

**Comment by yaelbh** [comment]
Otherwise this PR is ready for review.

**Comment by yaelbh** [comment]
@diego-plan9 it will be great if you can review it, or delegate the review. When done I will be able to rebase the other open pull requests, and to upload to PyPI.

**Comment by diego-plan9** [comment]
> I see that Travis failed for Python 3.5 because it cannot find the cpp simulator. It's strange because I thought that the cpp simulator was automatically compiled upon qiskit installation. It's even stranger because the checks pass for Python 3.6.

I missed the notification as it seems it was for another github username! For 3.5, it seems to be trying to used a cached version of the `qiskit` package, which indeed might have failed to compile during installation because of missing dependencies (for 3.5 we do not provide pre-built wheels, and for 0.5.6 we had to disable `cmake` as a python dependency due to issues with python 3.7). The most likely fix would be to manually install `cmake` in travis and recreate the cache: I'll look into it and try to find the time for a full review between today and tomorrow, but at a first glance it's looking good!

**Comment by diego-plan9** [comment]
It's looking good!

**Pull request merged**
