### PR TITLE
Fixed a linter error

### PR DESCRIPTION
**Pull request by yaelbh**
The linter complains:

************* Module test_projectq.test_qasm_simulator_projectq
E: 82, 8: Instance of 'QuantumCircuit' has no 'x' member (no-member)
E:101,12: Instance of 'QuantumCircuit' has no 'cx' member (no-member)

So I disabled this kind of errors for this file.
What I don't understand: qiskit-core is full of instances of "qc.cx" for some QuantumCircuit object qc, yet the linter is happy there. What's the difference?

### CODE REVIEW

**Comment by diego-plan9** [comment]
Nice catch! [Here](https://github.com/QISKit/qiskit-core/blob/master/.pylintrc#L300) is the difference:
```
generated-members=self.circuit.*,qcs.h,qc1.h,qc2.cx,qc.h,self.u1,self.cx,self.ccx,trial_circuit
```

The issue is that the gates are defined dynamically (ie. when `QuantumCircuit` is imported, it still does not contain the methods `QuantumCircuit.x()`, etc - that happens when the gate modules are imported), and the linter is not smart enough for picking up the added methods (probably for good reason - there is a limit on how smart the linter can be and how deep the introspection can go).

As a result, in `core` we added that line as a workaround (a slightly fragile one, as it will only act on the variables that have that specific names) - but a file-level disable sounds good as well in this case. Just for reference, in `qiskit-core` the policy is to try to avoid pylint disables in the main source files, but in the tests we are a bit more lenient indeed (and in this case seems very reasonable as well).

**Comment by yaelbh** [comment]
What's the process in this repository? @diego-plan9 can I interpret your answer as "approved"? How many reviewers are required to approve? Should I merge myself my approved pull requests?

**Comment by diego-plan9** [comment]
In `qiskit-core`, we basically follow a model where:
* we use the `approved` mark provided by Github (using their standard review system) to signal that the reviewer is fully happy with the changes.
* code owners (other than the person issuing the PR) need to explicitly review and approve the changes.
* all contributions are made using PRs (ie. no commits directly to master)

It's all about having as many eyes in the code as possible, and trust in the combined efforts of the repository members to improve the quality of the code and catch as many problems and ideas as possible. I think the same model would benefit this repo - probably with some adjustment/leniency during this initial sprint. I'll create an issue and subsequent PR for bringing up as many things (docs, github configuration, etc) as possible, and discuss!

In this particular PR ... sorry for not being clear with my previous answer, and not marking it as accepted! It is officially approved, merging :)

**Comment by yaelbh** [comment]
Many thanks for helping with this :smirk:. Two questions remain:
1. Is it sufficient to have one reviewer per pull request?
2. If all reviewers reviewed and approved a pull request that I issued, is it OK that I'm the one who merges it?

**Comment by jaygambetta** [comment]
Don’t worry too much while you get it into a version 0.1 state.  I don’t mind if you merge as admin and we discuss in issues for now.  Once it’s at 0.1 I think one reviewer is enough for addons

**Pull request merged**
